#!/bin/bash

readonly user=username # The script will be called as this user
readonly script=/full/path/to/rclone-jobman.sh
readonly jobFile=00_example # Filename for the desired job

sudo -u $user -i sh -c "$script $jobFile"
