#!/usr/bin/env bash

###################################################################
# Script Name : cron_file_example
# Description : For use with rclone-jobman. This is an example
#               for launching a job automatically using cron.
#               Modify the fiels below and put it on the desired
#               /etc/cron.[hourly|daily|monthly]/ directory.
# Args        : None
# Author      : CarlesCN
# E-mail      : drtlof@gmail.com
# License     : GNU General Public License v3.0
###################################################################

# Modify this
readonly user="user" # User that should call the script
readonly script_path="/full/path/to/rclone-jobman"
readonly job_file="filename" # Filename for the desired job (must be in user's $HOME/.config/rclone-jobman/jobs/)

# Do not touch this
sudo -u $user -i sh -c "$script_path $job_file"
